### ISSUE TITLE
Initialize Yarn Project

### ISSUE THREAD

**Issue by Tiernebre** [Tiernebre/pokemon-draft#3]
Using the Yarn CLI Tool, create a Node.js based project (package.json with node_modules) in the root of this folder.

Steps

-  Install Yarn by following the instructions at https://yarnpkg.com/getting-started
-  Use the Yarn Command Line application to initialize a project in this repository (something like `yarn init` should work)
-  Create a pull request with your changes and get an approval and merge it in.

**Comment by AlkaDas991** [comment]
@Tiernebre  I would like to work on this issue.
