### ISSUE TITLE
Create "Hello World" Script

### ISSUE THREAD

**Issue by Tiernebre** [Tiernebre/pokemon-draft#7]
We want to make sure our app can at least do something to ensure it can run properly.

Using JavaScript / Node.js: create a script that simply outputs to the console "Hello world!"

Tips:

- You can run node.js by typing `node` in the terminal, and you can run specific files using `node file.js`.
- Create a "script" inside of the package.json file that runs the command you used to run the "hello world" program.

**Comment by AlkaDas991** [comment]
@Tiernebre Since the issue is open, Can I work on it?
